use_frameworks!

platform :ios, '10.0'

target 'CustomSpinner_Example' do
  pod 'CustomSpinner', :path => '../'

  target 'CustomSpinner_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
